SELECT
  POPU_TRANSITION.PF_CODE AS 都道府県コード,
  PREFECTURE.PF_NAME AS 都道府県名,
  (
    SELECT
      TOTAL_AMT
    FROM
      POPU_TRANSITION
    WHERE
      SURVEY_YEAR = 2015,
      PF_CODE = POPU_TRANSITION_PARENT.PF_CODE
  )
  AS 総人口2015年
FROM
  POPU_TRANSITION AS POPU_TRANSITION_PARENT
    LEFT JOIN
  PREFECTURE
    ON
  POPU_TRANSITION_PARENT.PF_CODE = PREFECTURE.PF_CODE ;
